language: android
dist: trusty
sudo: required

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)
    - ANDROID_TAG=google_apis
    - ANDROID_ABI=x86
    - EMULATOR_API_LEVEL=28

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0-rc02
    - build-tools-27.0.3
    - android-27
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google-apis-$EMULATOR_API_LEVEL
  licenses:
    - android-sdk-license-.+
    - '.+'

before_script:
  - echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API_LEVEL
  - echo "y" | android update sdk -a --no-ui --filter sys-img-$ANDROID_ABI-android-$EMULATOR_API_LEVEL
  - android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -memory 1500 -no-accel -camera-back none -camera-front none -no-boot-anim -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew ktlint test install --info
  - ./gradlew install
  - cd KotlinConsumer
  - ./gradlew test --info
  - cd ../AndroidConsumer
  - ./gradlew test connectedCheck --info